// <auto-generated />
namespace DiDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-preview8-19405-04")]
    public sealed partial class initials : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initials));
        
        string IMigrationMetadata.Id
        {
            get { return "201908291238186_initials"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
